version: 2
jobs:
  build-staging:
    docker:
    # specify the version you desire here
    - image: docker:17.05.0-ce-git

    steps:
    - checkout
    - setup_remote_docker

    - run:
        name: Building docker image
        command: docker build -t polyhx/csgames-sts:latest .
    - run:
        name: Pushing docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push polyhx/csgames-sts:latest

  build-prod:
    docker:
    # specify the version you desire here
    - image: docker:17.05.0-ce-git

    steps:
    - checkout
    - setup_remote_docker

    - run:
        name: Building docker image
        command: docker build -t polyhx/csgames-sts:$CIRCLE_TAG .
    - run:
        name: Pushing docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push polyhx/csgames-sts:$CIRCLE_TAG

workflows:
  version: 2
  build-staging-if-master:
    jobs:
    - build-staging:
        filters:
          branches:
            only:
            - master
          tags:
            ignore: /.*/
  build-prod-if-tags:
    jobs:
    - build-prod:
        filters:
          tags:
            only: /^v([0-9.]+)$/
          branches:
            ignore: /.*/
